"""Replay committed project history and find the first supervisor divergence.

This mode is intentionally conservative:
- It compares prompts generated by the current code against the prompts that
  were actually sent historically.
- It only replays through exact committed checkpoints/tags.
- If a cycle required intermediate attempt state that was never checkpointed,
  the result is `unreplayable` rather than a guessed divergence.
"""

from __future__ import annotations

import copy
import difflib
import json
import re
import shutil
import subprocess
import tempfile
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional, Sequence, Tuple

from lagent_tablets.chat_history import ensure_chat_repo
from lagent_tablets.config import Config, Policy
from lagent_tablets.cycle import (
    _backfill_legacy_correspondence_hashes,
    _cleanup_check_payload_path,
    _coarse_restructure_candidate_nodes,
    _effective_correspondence_agents,
    _effective_soundness_agents,
    _invalidate_closed_node_status,
    _load_agent_previous_result,
    _load_existing_soundness_result,
    _load_previous_soundness_issues,
    _prepare_theorem_stating_worker_state,
    _proof_correspondence_frontier,
    _proof_scope_payload_path,
    _proof_soundness_frontier,
    _proof_verification_region,
    _repair_stale_legacy_correspondence_failures,
    _scoped_tablet_check_payload_path,
    _soundness_priority_order,
    _suspend_theorem_soundness_target,
    _theorem_stating_correspondence_frontier,
    _theorem_stating_has_correspondence_blockers,
    _theorem_stating_persisted_correspondence_nodes,
    _theorem_stating_preflight_error,
    _theorem_target_edit_mode,
    _theorem_target_edit_scope_payload_path,
    _theorem_target_repair_scope_payload_path,
    _theorem_target_scope,
)
from lagent_tablets.git_ops import _read_cycle_meta, get_cycle_history
from lagent_tablets.nl_cache import NLCache
from lagent_tablets.project_paths import project_runtime_skills_dir
from lagent_tablets.prompts import (
    build_correspondence_prompt,
    build_node_soundness_prompt,
    build_nl_proof_prompt,
    build_reviewer_prompt,
    build_theorem_stating_prompt,
    build_theorem_stating_reviewer_prompt,
    build_worker_prompt,
)
from lagent_tablets.state import (
    SupervisorState,
    TabletState,
    load_json,
    load_state,
    load_tablet,
    state_path,
    tablet_path,
)
from lagent_tablets.tablet import PREAMBLE_NAME, compute_target_impact_region


ARTIFACT_ATTEMPT_RE = re.compile(r"^(?P<base>.+?)(?:_attempt_(?P<attempt>\d{4}))?$")
WORKER_STAGE = "worker"
VERIFICATION_STAGE = "verification"
REVIEWER_STAGE = "reviewer"
STAGE_PREFIXES = {
    WORKER_STAGE: ("worker_handoff",),
    VERIFICATION_STAGE: ("correspondence_result", "nl_proof"),
    REVIEWER_STAGE: ("reviewer_decision",),
}


@dataclass
class PromptExpectation:
    stage: str
    artifact_base: str
    prompt: str


@dataclass
class ReplayResult:
    status: str  # match | diverged | unreplayable | error
    reason: str
    cycle: Optional[int] = None
    stage: str = ""
    artifact: str = ""
    historical_ref: str = ""
    historical_prompt: str = ""
    replay_prompt: str = ""
    diff: str = ""

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


@dataclass
class _ArtifactInfo:
    exact_id: str
    base: str
    attempt: int
    prompt: str


@dataclass
class _CycleArtifacts:
    by_exact: Dict[str, _ArtifactInfo]
    by_base: Dict[str, List[_ArtifactInfo]]

    def repeated_bases(self) -> Dict[str, List[int]]:
        repeated: Dict[str, List[int]] = {}
        for base, items in self.by_base.items():
            attempts = sorted({item.attempt for item in items})
            if len(attempts) > 1 or any(attempt > 1 for attempt in attempts):
                repeated[base] = attempts
        return repeated

    def stage_artifacts(self, stage: str) -> Dict[str, _ArtifactInfo]:
        prefixes = STAGE_PREFIXES[stage]
        selected: Dict[str, _ArtifactInfo] = {}
        for base, items in self.by_base.items():
            if not any(base.startswith(prefix) for prefix in prefixes):
                continue
            preferred = None
            for item in items:
                if item.attempt == 1:
                    preferred = item
                    break
            if preferred is None and len(items) == 1:
                preferred = items[0]
            if preferred is not None:
                selected[base] = preferred
        return selected


def _git(repo: Path, *args: str, check: bool = True) -> subprocess.CompletedProcess:
    return subprocess.run(
        ["git", *args],
        cwd=str(repo),
        capture_output=True,
        text=True,
        check=check,
    )


def _root_commit(repo: Path) -> Optional[str]:
    result = _git(repo, "rev-list", "--max-parents=0", "HEAD", check=False)
    if result.returncode != 0:
        return None
    lines = [line.strip() for line in result.stdout.splitlines() if line.strip()]
    return lines[0] if lines else None


def _ref_exists(repo: Path, ref: str) -> bool:
    return _git(repo, "rev-parse", "--verify", ref, check=False).returncode == 0


def _clone_for_analysis(original_repo: Path) -> Path:
    tmp_root = Path(tempfile.mkdtemp(prefix="lagent-history-replay-"))
    clone_path = tmp_root / "repo"
    subprocess.run(
        ["git", "clone", "--quiet", str(original_repo), str(clone_path)],
        check=True,
        capture_output=True,
        text=True,
    )
    lake_dir = original_repo / ".lake"
    if lake_dir.exists():
        shutil.copytree(lake_dir, clone_path / ".lake", dirs_exist_ok=True)
    return clone_path


def _checkout_ref(repo: Path, ref: str) -> None:
    subprocess.run(
        ["git", "checkout", "--force", "--quiet", ref],
        cwd=str(repo),
        check=True,
        capture_output=True,
        text=True,
    )


def _remap_repo_local_path(path: Optional[Path], old_repo: Path, new_repo: Path) -> Optional[Path]:
    if path is None:
        return None
    resolved = path.resolve()
    try:
        rel = resolved.relative_to(old_repo.resolve())
    except ValueError:
        return resolved
    return (new_repo / rel).resolve()


def _remap_config(config: Config, replay_repo: Path) -> Config:
    remapped = copy.deepcopy(config)
    remapped.repo_path = replay_repo.resolve()
    remapped.goal_file = _remap_repo_local_path(config.goal_file, config.repo_path, replay_repo) or config.goal_file
    remapped.state_dir = _remap_repo_local_path(config.state_dir, config.repo_path, replay_repo) or config.state_dir
    remapped.workflow.paper_tex_path = _remap_repo_local_path(
        config.workflow.paper_tex_path, config.repo_path, replay_repo
    )
    remapped.workflow.approved_axioms_path = (
        _remap_repo_local_path(config.workflow.approved_axioms_path, config.repo_path, replay_repo)
        or config.workflow.approved_axioms_path
    )
    remapped.workflow.human_input_path = (
        _remap_repo_local_path(config.workflow.human_input_path, config.repo_path, replay_repo)
        or config.workflow.human_input_path
    )
    remapped.workflow.input_request_path = (
        _remap_repo_local_path(config.workflow.input_request_path, config.repo_path, replay_repo)
        or config.workflow.input_request_path
    )
    remapped.chat.root_dir = remapped.state_dir / "chats"
    return remapped


def _normalize_prompt(prompt: str, original: Config, replay: Config) -> str:
    text = str(prompt or "")
    replacements: List[Tuple[str, str]] = []
    source_skills_dir = str((Path(__file__).resolve().parent.parent / "skills").resolve())
    for old, new in [
        (str(replay.state_dir), str(original.state_dir)),
        (str(replay.repo_path), str(original.repo_path)),
        (str(replay.goal_file), str(original.goal_file)),
        (str(replay.workflow.paper_tex_path or ""), str(original.workflow.paper_tex_path or "")),
        (str(replay.workflow.approved_axioms_path), str(original.workflow.approved_axioms_path)),
        (str(replay.workflow.human_input_path), str(original.workflow.human_input_path)),
        (str(replay.workflow.input_request_path), str(original.workflow.input_request_path)),
        (
            str(project_runtime_skills_dir(replay.state_dir).resolve()),
            source_skills_dir,
        ),
        (
            str(project_runtime_skills_dir(original.state_dir).resolve()),
            source_skills_dir,
        ),
        (
            str((replay.repo_path / ".agent-supervisor" / "skills").resolve()),
            source_skills_dir,
        ),
        (
            str((original.repo_path / ".agent-supervisor" / "skills").resolve()),
            source_skills_dir,
        ),
    ]:
        if old and old != new:
            replacements.append((old, new))
    replacements.sort(key=lambda pair: len(pair[0]), reverse=True)
    for old, new in replacements:
        text = text.replace(old, new)
    return text


def _prompt_diff(old: str, new: str, *, max_lines: int = 120) -> str:
    diff_lines = list(
        difflib.unified_diff(
            old.splitlines(),
            new.splitlines(),
            fromfile="historical",
            tofile="replay",
            lineterm="",
        )
    )
    if len(diff_lines) > max_lines:
        diff_lines = diff_lines[:max_lines] + ["... [diff truncated]"]
    return "\n".join(diff_lines)


def _load_cycle_artifacts(repo_path: Path, cycle: int) -> _CycleArtifacts:
    chats = ensure_chat_repo(repo_path)
    prefix = f"cycle-{cycle:04d}/"
    result = _git(chats, "ls-tree", "-r", "--name-only", f"cycle-{cycle}", "--", prefix, check=False)
    if result.returncode != 0:
        return _CycleArtifacts(by_exact={}, by_base={})

    prompt_artifacts: Dict[str, _ArtifactInfo] = {}
    by_base: Dict[str, List[_ArtifactInfo]] = {}
    prompt_paths = [
        line.strip() for line in result.stdout.splitlines()
        if line.strip().startswith(prefix) and line.strip().endswith("/prompt.txt")
    ]
    for prompt_path in prompt_paths:
        rel = prompt_path[len(prefix):]
        artifact_id = rel.split("/", 1)[0]
        prompt_result = _git(chats, "show", f"cycle-{cycle}:{prompt_path}", check=False)
        prompt = prompt_result.stdout if prompt_result.returncode == 0 else ""
        match = ARTIFACT_ATTEMPT_RE.fullmatch(artifact_id)
        if match:
            base = match.group("base")
            attempt_raw = match.group("attempt")
            attempt = int(attempt_raw) if attempt_raw else 1
        else:
            base = artifact_id
            attempt = 1
        info = _ArtifactInfo(exact_id=artifact_id, base=base, attempt=attempt, prompt=prompt)
        prompt_artifacts[artifact_id] = info
        by_base.setdefault(base, []).append(info)

    for items in by_base.values():
        items.sort(key=lambda item: (item.attempt, item.exact_id))
    return _CycleArtifacts(by_exact=prompt_artifacts, by_base=by_base)


def _first_attempt_artifact(cycle_artifacts: _CycleArtifacts, base: str) -> Optional[_ArtifactInfo]:
    items = cycle_artifacts.by_base.get(base, [])
    for item in items:
        if item.attempt == 1:
            return item
    return items[0] if len(items) == 1 else None


def _current_previous_outcome(history: List[Dict[str, Any]], cycle: int) -> Optional[Dict[str, Any]]:
    if cycle <= 1:
        return None
    previous = next((entry for entry in history if int(entry.get("cycle", 0) or 0) == cycle - 1), None)
    if not previous:
        return None
    result = {
        "outcome": previous.get("outcome", ""),
        "detail": previous.get("detail", ""),
    }
    if result["outcome"] == "REJECTED":
        result["rejection"] = {
            "summary": result["detail"],
            "results": previous.get("verification_results", []),
        }
    return result


def _prepare_runtime_state(config: Config, state: SupervisorState, tablet: TabletState, *, cycle: int) -> None:
    _invalidate_closed_node_status(config, tablet, cycle=cycle)


def _ensure_proof_active_node(state: SupervisorState, tablet: TabletState) -> None:
    current = state.active_node or tablet.active_node
    if state.phase == "proof_formalization" and current and current in tablet.nodes and tablet.nodes[current].status == "closed":
        current = ""
    if not current:
        if state.phase == "proof_complete_style_cleanup":
            cleanup_nodes = [n for n, node in sorted(tablet.nodes.items()) if node.kind != "preamble"]
            current = cleanup_nodes[0] if cleanup_nodes else ""
        else:
            open_nodes = [n for n, node in sorted(tablet.nodes.items()) if node.status == "open" and node.kind != "preamble"]
            current = open_nodes[0] if open_nodes else ""
    state.active_node = current
    tablet.active_node = current


def _stage_inventory_has_retries(cycle_artifacts: _CycleArtifacts, stage: str) -> Dict[str, List[int]]:
    prefixes = STAGE_PREFIXES[stage]
    return {
        base: attempts
        for base, attempts in cycle_artifacts.repeated_bases().items()
        if any(base.startswith(prefix) for prefix in prefixes)
    }


def _compare_prompt(
    *,
    original_config: Config,
    replay_config: Config,
    historical: _ArtifactInfo,
    replay_prompt: str,
    cycle: int,
    stage: str,
) -> Optional[ReplayResult]:
    normalized_historical = _normalize_prompt(historical.prompt, original_config, replay_config)
    normalized_replay = _normalize_prompt(replay_prompt, original_config, replay_config)
    if normalized_replay == normalized_historical:
        return None
    return ReplayResult(
        status="diverged",
        reason="Prompt text differs from historical run.",
        cycle=cycle,
        stage=stage,
        artifact=historical.exact_id,
        historical_ref=f"cycle-{cycle}",
        historical_prompt=normalized_historical,
        replay_prompt=normalized_replay,
        diff=_prompt_diff(normalized_historical, normalized_replay),
    )


def _read_output_log(repo_path: Path, cycle: int, artifact: str) -> str:
    chats = ensure_chat_repo(repo_path)
    rel = f"cycle-{cycle:04d}/{artifact}/output.log"
    result = _git(chats, "show", f"cycle-{cycle}:{rel}", check=False)
    return result.stdout if result.returncode == 0 else ""


def _load_tag_json(repo: Path, ref: str, rel_path: str) -> Any:
    result = _git(repo, "show", f"{ref}:{rel_path}", check=False)
    if result.returncode != 0:
        return None
    try:
        return json.loads(result.stdout)
    except json.JSONDecodeError:
        return None


def _current_phase_for_cycle(sim_repo: Path, phase: str) -> Tuple[SupervisorState, TabletState]:
    state = load_state(state_path(sim_repo / ".agent-supervisor"))
    tablet = load_tablet(tablet_path(sim_repo / ".agent-supervisor"))
    if state.cycle == 0:
        state.phase = phase
    return state, tablet


def _theorem_worker_prompt(
    config: Config,
    state: SupervisorState,
    tablet: TabletState,
    policy: Policy,
    *,
    previous_outcome: Optional[Dict[str, Any]],
    cycle: int,
) -> Tuple[str, str]:
    nl_cache = NLCache(config.state_dir / "nl_cache.json")
    _prepare_theorem_stating_worker_state(config, state, tablet, policy, nl_cache=nl_cache)
    preflight_error = _theorem_stating_preflight_error(state)
    if preflight_error:
        return "", preflight_error
    target = state.theorem_soundness_target.strip()
    mode = _theorem_target_edit_mode(state)
    log_dir = config.state_dir / "logs" / f"cycle-{cycle:04d}"
    authorized_region = sorted(_theorem_target_scope(config.repo_path, target)) if target else []
    scoped_payload = _scoped_tablet_check_payload_path(log_dir) if target and mode == "restructure" else None
    repair_payload = _theorem_target_repair_scope_payload_path(log_dir) if target and mode == "repair" else None
    edit_payload = _theorem_target_edit_scope_payload_path(log_dir) if target and mode == "restructure" else None
    return (
        build_theorem_stating_prompt(
            config,
            state,
            tablet,
            policy,
            previous_outcome=previous_outcome,
            authorized_region=authorized_region,
            scoped_tablet_check_payload_path=scoped_payload,
            repair_scope_check_payload_path=repair_payload,
            edit_scope_check_payload_path=edit_payload,
        ),
        "",
    )


def _proof_worker_prompt(
    config: Config,
    state: SupervisorState,
    tablet: TabletState,
    policy: Policy,
    *,
    previous_outcome: Optional[Dict[str, Any]],
    cycle: int,
) -> str:
    _ensure_proof_active_node(state, tablet)
    node_name = state.active_node or tablet.active_node
    node_meta = tablet.nodes.get(node_name)
    difficulty = node_meta.difficulty if node_meta else "hard"
    log_dir = config.state_dir / "logs" / f"cycle-{cycle:04d}"
    cleanup_payload = _cleanup_check_payload_path(log_dir) if state.phase == "proof_complete_style_cleanup" else None
    proof_payload = _proof_scope_payload_path(log_dir, difficulty) if state.phase == "proof_formalization" else None
    return build_worker_prompt(
        config,
        state,
        tablet,
        policy,
        previous_outcome=previous_outcome,
        difficulty=difficulty,
        cleanup_check_payload_path=cleanup_payload,
        proof_scope_check_payload_path=proof_payload,
    )


def _load_correspondence_agent_result(repo: Path, index: int) -> Optional[Dict[str, Any]]:
    path = repo / f"correspondence_result_{index}.json"
    return load_json(path, default=None) if path.exists() else None


def _load_single_correspondence_result(repo: Path) -> Optional[Dict[str, Any]]:
    path = repo / "correspondence_result.json"
    return load_json(path, default=None) if path.exists() else None


def _load_single_soundness_batch(repo: Path) -> Optional[Dict[str, Any]]:
    path = repo / "nl_proof_result.json"
    return load_json(path, default=None) if path.exists() else None


def _aggregate_correspondence_results(
    repo: Path,
    corr_nodes: List[str],
    agents: List[Any],
) -> Optional[Dict[str, Any]]:
    if not corr_nodes:
        return None
    if len(agents) >= 2:
        agent_results: List[Dict[str, Any]] = []
        for i, agent in enumerate(agents):
            selected_index = getattr(agent, "selected_index", i)
            data = _load_correspondence_agent_result(repo, selected_index)
            if not isinstance(data, dict):
                return None
            agent_results.append({
                "agent": agent.label or f"{agent.provider}/{agent.model}",
                "index": selected_index,
                "ok": True,
                **data,
            })
        overalls = [r.get("overall", "ERROR") for r in agent_results]
        all_approve = all(o == "APPROVE" for o in overalls)
        all_reject = all(o == "REJECT" for o in overalls)
        if all_approve or all_reject:
            overall = "APPROVE" if all_approve else "REJECT"
            return {
                "check": "correspondence",
                "overall": overall,
                "summary": f"Unanimous {overall} from {len(agent_results)} agents",
                "node_names": list(corr_nodes),
                "agent_results": agent_results,
            }
        disagree_detail = ", ".join(
            f"{result.get('agent', '?')}: {result.get('overall', '?')}"
            for result in agent_results
        )
        return {
            "check": "correspondence",
            "overall": "DISAGREE",
            "summary": f"Agents disagree: {disagree_detail}. Reviewer must arbitrate.",
            "node_names": list(corr_nodes),
            "agent_results": agent_results,
        }
    data = _load_single_correspondence_result(repo)
    if not isinstance(data, dict):
        return None
    return {"check": "correspondence", "node_names": list(corr_nodes), **data}


def _aggregate_soundness_results(
    config: Config,
    tablet: TabletState,
    proof_nodes: List[str],
    agents: List[Any],
    *,
    disagree_bias: str,
) -> Optional[List[Dict[str, Any]]]:
    if not proof_nodes:
        return None
    if len(agents) < 2:
        data = _load_single_soundness_batch(config.repo_path)
        if not isinstance(data, dict):
            return None
        return [{"check": "nl_proof", "node_names": list(proof_nodes), **data}]

    check_nodes = [
        name for name in proof_nodes
        if name in tablet.nodes and tablet.nodes[name].kind != "preamble"
    ]
    check_nodes = _soundness_priority_order(config.repo_path, tablet, check_nodes)
    node_verdicts: List[Dict[str, Any]] = []
    structural_issues: List[str] = []
    for node_name in check_nodes:
        if tablet.nodes[node_name].status == "closed":
            continue
        node_results: List[Dict[str, Any]] = []
        for i, agent in enumerate(agents):
            selected_index = getattr(agent, "selected_index", i)
            existing = _load_existing_soundness_result(
                config,
                node_name=node_name,
                agent_index=selected_index,
                agent_label=agent.label or f"{agent.provider}/{agent.model}",
            )
            if existing is None:
                path = config.repo_path / f"nl_proof_{node_name}_{selected_index}.json"
                data = load_json(path, default=None) if path.exists() else None
                if not isinstance(data, dict):
                    return None
                existing = {
                    "agent": agent.label or f"{agent.provider}/{agent.model}",
                    "node": node_name,
                    "index": selected_index,
                    "ok": True,
                    **data,
                }
            node_results.append(existing)
        overalls = [result.get("overall", "ERROR") for result in node_results]
        soundness_decisions = [
            result.get("soundness", {}).get("decision", "?")
            if isinstance(result.get("soundness"), dict)
            else "?"
            for result in node_results
        ]
        has_structural = any(decision == "STRUCTURAL" for decision in soundness_decisions)
        all_approve = all(overall == "APPROVE" for overall in overalls)
        all_reject = all(overall == "REJECT" for overall in overalls)
        panel_split = len(node_results) == 2 and len(set(overalls)) > 1
        if all_approve:
            node_overall = "APPROVE"
        elif all_reject:
            node_overall = "REJECT"
        elif panel_split:
            node_overall = "APPROVE" if disagree_bias == "approve" else "REJECT"
        else:
            node_overall = "REJECT"
        verdict: Dict[str, Any] = {
            "node": node_name,
            "agent_results": node_results,
            "overall": node_overall,
        }
        if panel_split:
            verdict["panel_split"] = True
            verdict["disagree_bias"] = disagree_bias
        if has_structural:
            verdict["structural"] = True
            structural_issues.append(node_name)
        node_verdicts.append(verdict)

    all_approve = all(verdict["overall"] == "APPROVE" for verdict in node_verdicts)
    summary_parts: List[str] = []
    if structural_issues:
        summary_parts.append(f"STRUCTURAL issues in: {structural_issues}")
    failed_nodes = [verdict["node"] for verdict in node_verdicts if verdict["overall"] != "APPROVE"]
    if failed_nodes:
        summary_parts.append(f"Failed: {failed_nodes}")
    return [{
        "check": "nl_proof",
        "overall": "APPROVE" if all_approve else "REJECT",
        "summary": "; ".join(summary_parts) if summary_parts else f"All {len(node_verdicts)} nodes sound",
        "structural_issues": structural_issues,
        "node_names": [verdict["node"] for verdict in node_verdicts],
        "node_verdicts": node_verdicts,
    }]


def _plan_verification(
    config: Config,
    state: SupervisorState,
    tablet: TabletState,
    policy: Policy,
    *,
    cycle: int,
    worker_ref: str,
    verification_ref: str,
) -> Tuple[List[PromptExpectation], List[Dict[str, Any]], Optional[ReplayResult]]:
    log_dir = config.state_dir / "logs" / f"cycle-{cycle:04d}"
    expectations: List[PromptExpectation] = []
    results: List[Dict[str, Any]] = []
    nl_cache = NLCache(config.state_dir / "nl_cache.json")

    corr_nodes_base: List[str] = []
    proof_nodes_base: List[str] = []
    persisted_correspondence_blocked = False
    force_correspondence_node_names: List[str] = []
    soundness_target_node: Optional[str] = None

    if state.phase == "theorem_stating":
        _backfill_legacy_correspondence_hashes(tablet, config.repo_path)
        _repair_stale_legacy_correspondence_failures(tablet, state, config.repo_path)
        corr_nodes_base = _theorem_stating_correspondence_frontier(
            tablet,
            config.repo_path,
            forced_nodes=_theorem_stating_persisted_correspondence_nodes(tablet, state),
        )
        proof_nodes_base = [
            name for name in tablet.nodes
            if name != PREAMBLE_NAME and tablet.nodes[name].kind != "preamble"
        ]
        persisted_correspondence_blocked = _theorem_stating_has_correspondence_blockers(state)
        force_correspondence_node_names = _theorem_stating_persisted_correspondence_nodes(tablet, state)
        soundness_target_node = state.theorem_soundness_target or None
    elif state.phase == "proof_formalization":
        worker_meta = _read_cycle_meta(config.repo_path, worker_ref)
        outcome = str(worker_meta.get("outcome", "") or "").strip().upper()
        if outcome == "PROGRESS":
            previous_ref = _root_commit(config.repo_path) if cycle == 1 else f"cycle-{cycle - 1}"
            if cycle > 1 and not _ref_exists(config.repo_path, previous_ref):
                return expectations, results, ReplayResult(
                    status="unreplayable",
                    reason=f"Missing previous final ref {previous_ref} while planning proof verification.",
                    cycle=cycle,
                    stage=VERIFICATION_STAGE,
                )
            previous_names: set[str] = set()
            if cycle > 1:
                _checkout_ref(config.repo_path, previous_ref)
                previous_tablet = load_tablet(tablet_path(config))
                previous_names = {
                    name for name, node in previous_tablet.nodes.items()
                    if node.kind != "preamble"
                }
                _checkout_ref(config.repo_path, worker_ref)
                state = load_state(state_path(config))
                tablet = load_tablet(tablet_path(config))
                _prepare_runtime_state(config, state, tablet, cycle=cycle)
            current_names = {
                name for name, node in tablet.nodes.items()
                if node.kind != "preamble"
            }
            created_nodes = sorted(current_names - previous_names)
            changed_nodes = sorted(
                {
                    name for name in created_nodes
                }
                | {
                    Path(path).stem
                    for path in _git(config.repo_path, "diff", "--name-only", previous_ref, worker_ref, "--", "Tablet/", check=False).stdout.splitlines()
                    if path.endswith(".lean") or path.endswith(".tex")
                }
            )
            verification_region = _proof_verification_region(config.repo_path, changed_nodes)
            corr_nodes_base = _proof_correspondence_frontier(
                tablet,
                config.repo_path,
                candidate_names=verification_region,
            )
            proof_nodes_base = _proof_soundness_frontier(
                tablet,
                config.repo_path,
                candidate_names=verification_region,
            )
        else:
            corr_nodes_base = []
            proof_nodes_base = []
    else:
        return expectations, results, None

    corr_nodes = list(corr_nodes_base)
    cached_corr_nodes: List[str] = []
    forced_corr = {str(name) for name in force_correspondence_node_names if str(name).strip()}
    if corr_nodes_base:
        uncached = set(nl_cache.filter_uncached(config.repo_path, corr_nodes_base, "correspondence"))
        corr_nodes = [name for name in corr_nodes_base if name in uncached or name in forced_corr]
        cached_corr_nodes = [name for name in corr_nodes_base if name not in set(corr_nodes)]
    if cached_corr_nodes:
        results.append({
            "check": "correspondence",
            "overall": "APPROVE",
            "summary": "cached",
            "node_names": cached_corr_nodes,
        })
    if corr_nodes:
        corr_agents = _effective_correspondence_agents(config, policy)
        if len(corr_agents) >= 2:
            for i, agent in enumerate(corr_agents):
                selected_index = getattr(agent, "selected_index", i)
                prompt = build_correspondence_prompt(
                    config,
                    tablet,
                    node_names=corr_nodes,
                    paper_tex="",
                    human_input=state.human_input,
                    output_file=f"correspondence_result_{selected_index}.json",
                    previous_results=[
                        _load_agent_previous_result(config.repo_path, selected_index)
                    ] if _load_agent_previous_result(config.repo_path, selected_index) else None,
                )
                expectations.append(
                    PromptExpectation(
                        stage=VERIFICATION_STAGE,
                        artifact_base=f"correspondence_result_{selected_index}",
                        prompt=prompt,
                    )
                )
            _checkout_ref(config.repo_path, verification_ref)
            results.append(_aggregate_correspondence_results(config.repo_path, corr_nodes, corr_agents) or {
                "check": "correspondence",
                "overall": "ERROR",
                "summary": "Missing correspondence artifacts in historical verification checkpoint.",
                "node_names": corr_nodes,
            })
            _checkout_ref(config.repo_path, worker_ref)
        else:
            prompt = build_correspondence_prompt(
                config,
                tablet,
                node_names=corr_nodes,
                paper_tex="",
                human_input=state.human_input,
            )
            expectations.append(
                PromptExpectation(
                    stage=VERIFICATION_STAGE,
                    artifact_base="correspondence_result",
                    prompt=prompt,
                )
            )
            _checkout_ref(config.repo_path, verification_ref)
            data = _load_single_correspondence_result(config.repo_path)
            results.append(
                {"check": "correspondence", "node_names": corr_nodes, **data}
                if isinstance(data, dict)
                else {
                    "check": "correspondence",
                    "overall": "ERROR",
                    "summary": "Missing correspondence_result.json in historical verification checkpoint.",
                    "node_names": corr_nodes,
                }
            )
            _checkout_ref(config.repo_path, worker_ref)

    corr_overall = "APPROVE"
    saw_corr = False
    for result in results:
        if result.get("check") == "correspondence":
            saw_corr = True
            corr_overall = str(result.get("overall", "?") or "?")
    if persisted_correspondence_blocked and not saw_corr:
        corr_overall = "REJECT"
        results.append({
            "check": "correspondence",
            "overall": "REJECT",
            "summary": (
                "Persisted correspondence/paper-faithfulness blockers remain open from a previous cycle; "
                "soundness stays gated until they are explicitly rechecked and cleared."
            ),
            "node_names": [],
        })
    if corr_overall != "APPROVE":
        return expectations, results, None

    proof_nodes = list(proof_nodes_base)
    if proof_nodes_base:
        proof_nodes = nl_cache.filter_uncached(config.repo_path, proof_nodes_base, "soundness")
    if proof_nodes and soundness_target_node is not None:
        if soundness_target_node in proof_nodes:
            proof_nodes = [soundness_target_node]
        else:
            proof_nodes = _soundness_priority_order(config.repo_path, tablet, proof_nodes)[:1]
    if not proof_nodes and proof_nodes_base:
        results.append({
            "check": "nl_proof",
            "overall": "APPROVE",
            "summary": "cached",
            "node_names": [],
        })
        return expectations, results, None
    if not proof_nodes:
        return expectations, results, None

    soundness_agents = _effective_soundness_agents(config, policy)
    if len(soundness_agents) >= 2:
        ordered_nodes = _soundness_priority_order(config.repo_path, tablet, proof_nodes)
        for node_name in ordered_nodes:
            if node_name not in tablet.nodes or tablet.nodes[node_name].status == "closed":
                continue
            for i, agent in enumerate(soundness_agents):
                selected_index = getattr(agent, "selected_index", i)
                prompt = build_node_soundness_prompt(
                    config,
                    tablet,
                    node_name=node_name,
                    paper_tex="",
                    human_input=state.human_input,
                    output_file=f"nl_proof_{node_name}_{selected_index}.json",
                    previous_issues=_load_previous_soundness_issues(
                        config.repo_path,
                        node_name=node_name,
                        agent_index=selected_index,
                    ),
                )
                expectations.append(
                    PromptExpectation(
                        stage=VERIFICATION_STAGE,
                        artifact_base=f"nl_proof_{node_name}_{selected_index}",
                        prompt=prompt,
                    )
                )
        _checkout_ref(config.repo_path, verification_ref)
        aggregated = _aggregate_soundness_results(
            config,
            tablet,
            proof_nodes,
            soundness_agents,
            disagree_bias=policy.verification.soundness_disagree_bias,
        )
        if aggregated is None:
            aggregated = [{
                "check": "nl_proof",
                "overall": "ERROR",
                "summary": "Missing soundness artifacts in historical verification checkpoint.",
                "node_names": list(proof_nodes),
            }]
        results.extend(aggregated)
        _checkout_ref(config.repo_path, worker_ref)
    else:
        prompt = build_nl_proof_prompt(
            config,
            tablet,
            node_names=proof_nodes,
            paper_tex="",
            human_input=state.human_input,
            output_file="nl_proof_result.json",
        )
        expectations.append(
            PromptExpectation(
                stage=VERIFICATION_STAGE,
                artifact_base="nl_proof_result",
                prompt=prompt,
            )
        )
        _checkout_ref(config.repo_path, verification_ref)
        data = _load_single_soundness_batch(config.repo_path)
        results.append(
            {"check": "nl_proof", "node_names": proof_nodes, **data}
            if isinstance(data, dict)
            else {
                "check": "nl_proof",
                "overall": "ERROR",
                "summary": "Missing nl_proof_result.json in historical verification checkpoint.",
                "node_names": list(proof_nodes),
            }
        )
        _checkout_ref(config.repo_path, worker_ref)

    return expectations, results, None


def _worker_output_for_cycle(repo_path: Path, cycle: int) -> str:
    artifacts = _load_cycle_artifacts(repo_path, cycle)
    worker = _first_attempt_artifact(artifacts, "worker_handoff")
    if worker is None:
        return ""
    return _read_output_log(repo_path, cycle, worker.exact_id)


def _reviewer_prompt(
    config: Config,
    state: SupervisorState,
    tablet: TabletState,
    policy: Policy,
    *,
    historical_repo: Path,
    cycle: int,
    historical_results: List[Dict[str, Any]],
    cycle_meta: Dict[str, Any],
) -> Tuple[bool, str]:
    worker_handoff = load_json(config.repo_path / "worker_handoff.json", default=None)
    worker_output = _worker_output_for_cycle(historical_repo, cycle)
    if state.phase == "theorem_stating":
        reviewer_state = _suspend_theorem_soundness_target(state) if any(
            str(result.get("check", "")).strip() == "correspondence" and str(result.get("overall", "")).strip().upper() != "APPROVE"
            for result in historical_results
        ) else state
        prompt = build_theorem_stating_reviewer_prompt(
            config,
            reviewer_state,
            tablet,
            policy,
            worker_handoff=worker_handoff if isinstance(worker_handoff, dict) else None,
            worker_output=worker_output[-15000:] if worker_output else "",
            nl_verification=historical_results if historical_results else None,
            main_result_issues=[],
            unsupported_nodes=[],
            validation_summary={
                "outcome": cycle_meta.get("outcome", ""),
                "detail": cycle_meta.get("detail", ""),
                "consecutive_invalids": (
                    state.validation_summary.get("consecutive_invalids", 0)
                    if isinstance(state.validation_summary, dict)
                    else 0
                ),
            },
            available_reset_checkpoints=[],
        )
        return True, prompt

    outcome = str(cycle_meta.get("outcome", "") or "").strip().upper()
    needs_nl_review = bool(historical_results)
    consecutive_invalids = (
        state.validation_summary.get("consecutive_invalids", 0)
        if isinstance(state.validation_summary, dict)
        else 0
    )
    invalid_escalation_threshold = 3
    needs_reviewer = (
        outcome in ("PROGRESS", "NO_PROGRESS")
        or needs_nl_review
        or outcome == "REJECTED"
        or (outcome == "INVALID" and consecutive_invalids >= invalid_escalation_threshold)
        or state.phase == "proof_complete_style_cleanup"
    )
    if not needs_reviewer:
        return False, ""
    prompt = build_reviewer_prompt(
        config,
        state,
        tablet,
        policy,
        worker_handoff=worker_handoff if isinstance(worker_handoff, dict) else None,
        worker_output=worker_output[-20000:] if worker_output else "",
        validation_summary={
            "outcome": outcome,
            "detail": cycle_meta.get("detail", ""),
            "consecutive_invalids": consecutive_invalids,
        },
        nl_verification=historical_results if historical_results else None,
    )
    return True, prompt


def _compare_expected_stage_prompts(
    *,
    original_config: Config,
    replay_config: Config,
    cycle: int,
    stage: str,
    historical_artifacts: _CycleArtifacts,
    expected: Sequence[PromptExpectation],
) -> Optional[ReplayResult]:
    repeated = _stage_inventory_has_retries(historical_artifacts, stage)
    if repeated:
        repeated_text = ", ".join(
            f"{base}: attempts {attempts}" for base, attempts in sorted(repeated.items())
        )
        return ReplayResult(
            status="unreplayable",
            reason=f"Historical {stage} stage used repeated attempts that were not checkpointed: {repeated_text}",
            cycle=cycle,
            stage=stage,
        )

    historical_stage = historical_artifacts.stage_artifacts(stage)
    expected_map = {item.artifact_base: item for item in expected}
    historical_bases = set(historical_stage.keys())
    expected_bases = set(expected_map.keys())
    if historical_bases != expected_bases:
        return ReplayResult(
            status="diverged",
            reason=(
                f"{stage.capitalize()} prompt set differs. "
                f"historical={sorted(historical_bases)} replay={sorted(expected_bases)}"
            ),
            cycle=cycle,
            stage=stage,
        )

    for base in sorted(expected_bases):
        historical = historical_stage[base]
        divergence = _compare_prompt(
            original_config=original_config,
            replay_config=replay_config,
            historical=historical,
            replay_prompt=expected_map[base].prompt,
            cycle=cycle,
            stage=stage,
        )
        if divergence is not None:
            return divergence
    return None


def find_first_history_divergence(
    config: Config,
    policy: Policy,
    *,
    max_cycle: Optional[int] = None,
) -> ReplayResult:
    history = get_cycle_history(config.repo_path)
    if max_cycle is not None:
        history = [entry for entry in history if int(entry.get("cycle", 0) or 0) <= max_cycle]
    if not history:
        return ReplayResult(status="match", reason="No committed cycle history found.")

    original_repo = config.repo_path.resolve()
    replay_repo = _clone_for_analysis(original_repo)
    replay_config = _remap_config(config, replay_repo)

    try:
        root = _root_commit(replay_repo)
        if not root:
            return ReplayResult(status="error", reason="Could not resolve initial commit in replay clone.")

        for entry in history:
            cycle = int(entry.get("cycle", 0) or 0)
            historical_artifacts = _load_cycle_artifacts(config.repo_path, cycle)

            previous_outcome = _current_previous_outcome(history, cycle)
            previous_invalid = previous_outcome and str(previous_outcome.get("outcome", "")).strip().upper() == "INVALID"

            pre_ref = root if cycle == 1 else f"cycle-{cycle - 1}"
            if cycle > 1 and not _ref_exists(config.repo_path, pre_ref):
                return ReplayResult(
                    status="unreplayable",
                    reason=f"Missing historical ref {pre_ref}.",
                    cycle=cycle,
                    stage=WORKER_STAGE,
                )

            _checkout_ref(replay_repo, pre_ref)
            state, tablet = _current_phase_for_cycle(replay_repo, config.workflow.start_phase)
            _prepare_runtime_state(replay_config, state, tablet, cycle=max(cycle - 1, state.cycle))

            if state.phase == "theorem_stating":
                prompt, preflight_error = _theorem_worker_prompt(
                    replay_config,
                    state,
                    tablet,
                    policy,
                    previous_outcome=previous_outcome,
                    cycle=cycle,
                )
                if preflight_error:
                    return ReplayResult(
                        status="diverged",
                        reason=f"Current theorem-stating preflight would stop before prompting: {preflight_error}",
                        cycle=cycle,
                        stage=WORKER_STAGE,
                    )
            else:
                prompt = _proof_worker_prompt(
                    replay_config,
                    state,
                    tablet,
                    policy,
                    previous_outcome=previous_outcome,
                    cycle=cycle,
                )

            worker_artifact = _first_attempt_artifact(historical_artifacts, "worker_handoff")
            if worker_artifact is None:
                return ReplayResult(
                    status="unreplayable",
                    reason="Historical worker prompt not found.",
                    cycle=cycle,
                    stage=WORKER_STAGE,
                )
            worker_divergence = _compare_prompt(
                original_config=config,
                replay_config=replay_config,
                historical=worker_artifact,
                replay_prompt=prompt,
                cycle=cycle,
                stage=WORKER_STAGE,
            )
            if worker_divergence is not None:
                if previous_invalid:
                    worker_divergence.status = "unreplayable"
                    worker_divergence.reason = (
                        "Previous committed cycle was INVALID, and exact worker prompt replay "
                        "cannot recover the historical build-output context from git history."
                    )
                return worker_divergence

            worker_retries = _stage_inventory_has_retries(historical_artifacts, WORKER_STAGE)
            if worker_retries:
                repeated_text = ", ".join(
                    f"{base}: attempts {attempts}" for base, attempts in sorted(worker_retries.items())
                )
                return ReplayResult(
                    status="unreplayable",
                    reason=f"Historical worker stage used repeated attempts that were not checkpointed: {repeated_text}",
                    cycle=cycle,
                    stage=WORKER_STAGE,
                )

            worker_ref = f"cycle-{cycle}-worker"
            if not _ref_exists(config.repo_path, worker_ref):
                return ReplayResult(
                    status="unreplayable",
                    reason=f"Missing historical worker checkpoint {worker_ref}.",
                    cycle=cycle,
                    stage=VERIFICATION_STAGE,
                )

            verification_ref = f"cycle-{cycle}-verification"
            if not _ref_exists(config.repo_path, verification_ref):
                return ReplayResult(
                    status="unreplayable",
                    reason=f"Missing historical verification checkpoint {verification_ref}.",
                    cycle=cycle,
                    stage=VERIFICATION_STAGE,
                )

            _checkout_ref(replay_repo, worker_ref)
            state = load_state(state_path(replay_config))
            tablet = load_tablet(tablet_path(replay_config))
            _prepare_runtime_state(replay_config, state, tablet, cycle=cycle)

            expected_verification, verification_results, planning_issue = _plan_verification(
                replay_config,
                state,
                tablet,
                policy,
                cycle=cycle,
                worker_ref=worker_ref,
                verification_ref=verification_ref,
            )
            if planning_issue is not None:
                return planning_issue
            verification_divergence = _compare_expected_stage_prompts(
                original_config=config,
                replay_config=replay_config,
                cycle=cycle,
                stage=VERIFICATION_STAGE,
                historical_artifacts=historical_artifacts,
                expected=expected_verification,
            )
            if verification_divergence is not None:
                return verification_divergence

            _checkout_ref(replay_repo, verification_ref)
            state = load_state(state_path(replay_config))
            tablet = load_tablet(tablet_path(replay_config))
            _prepare_runtime_state(replay_config, state, tablet, cycle=cycle)
            reviewer_needed, reviewer_prompt = _reviewer_prompt(
                replay_config,
                state,
                tablet,
                policy,
                historical_repo=config.repo_path,
                cycle=cycle,
                historical_results=verification_results,
                cycle_meta=_read_cycle_meta(config.repo_path, verification_ref),
            )
            expected_reviewer = (
                [PromptExpectation(stage=REVIEWER_STAGE, artifact_base="reviewer_decision", prompt=reviewer_prompt)]
                if reviewer_needed
                else []
            )
            reviewer_divergence = _compare_expected_stage_prompts(
                original_config=config,
                replay_config=replay_config,
                cycle=cycle,
                stage=REVIEWER_STAGE,
                historical_artifacts=historical_artifacts,
                expected=expected_reviewer,
            )
            if reviewer_divergence is not None:
                return reviewer_divergence

        return ReplayResult(status="match", reason="Current code matches recorded prompts through the checked committed history.")
    finally:
        shutil.rmtree(replay_repo.parent, ignore_errors=True)
